### ISSUE TITLE
Unable to join a lobby

### ISSUE THREAD

**Issue by Alex-cendre** [BetterOtherRoles/BetterOtherRoles#2]
**Describe the bug**
When joining the game, the player appears as green with "???" before disappearing from the lobby (this lasts for 2 or 3 seconds). If he creates the lobby, we can join it, play a game, but when returning to the spaceship, we get stuck and then get kicked out of the lobby (the player who created it gets kicked out as well). We have remained on version 1.1.7 to be able to play with this player.

**To Reproduce**
It's quite complicated to reproduce since it only happens to one player in the group. He just joins the lobby like he usually does.

**Expected behavior**
Since he has the same version as all the other players, he should be able to join us normally.

**Screenshots**
https://media.discordapp.net/attachments/900819305204162582/1107694848196214815/image.png

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version  v2023.3.28s
 - BetterOtherRoles Version from 1.1.11 to 1.2.9. 

**Additional context**
I myself encountered an issue before the updates last weekend. It was difficult for me to launch the game, and I received the error message "Collecting from unknown thread." It is now resolved. I'm not sure if that information can be helpful.

**Comment by EnoPM** [comment]
Hello,
I've seen this issue happen before with other players who live far away from the private server location and only on the newer versions of the mod.
I think it comes from the private servers timeout (2500 milliseconds by default). I added a private server located in Europe (France) called "BOR [EU]" on which I put a timeout of 10000 miliseconds to see if it could allow people who live far away to join the lobbies.
If your friend has the opportunity to test this server and give me feedback on whether it worked or not it would help me a lot in my investigation.

Regarding the "Collecting from unknown thread" error message, I also had feedback from users since version 1.2.8 of the mod. However, I have never managed to reproduce the problem and I have not been able to investigate further.

**Comment by Alex-cendre** [comment]
Hello,

I just tested it with him and it doesn't work. The player lives in Belgium and sometimes experiences disconnections, but never to the extent of not being able to join us at all. He receives the following message: "You disconnected from the server. The remote sent a disconnect request." I checked his modded folder, and everything seems to be in order.

As for the game startup error, it has been reported in the past on Discord server of The Other Roles. In recent versions of BOR, I've received the message once out of ten launches. It's no longer bothersome to me.

**Comment by EnoPM** [comment]
> I just tested it with him and it doesn't work
Have you tested on the **BOR [EU]** server?

**Comment by Alex-cendre** [comment]
Yes, we have.

**Comment by EnoPM** [comment]
With the latest version the problem should no longer occur.
